"""Platform vocabularies: audit actions, outbox statuses, job statuses.

These values double as the CHECK constraints in migration 0005 — keep the two in
sync. Audit actions are domain-specific event names (e.g. `SCHOOL_CREATED`), not
generic CRUD verbs, so a reader can reconstruct what happened from the log alone.
"""
from __future__ import annotations

from enum import StrEnum


class AuditAction(StrEnum):
    ORGANIZATION_CREATED = "ORGANIZATION_CREATED"
    ORGANIZATION_UPDATED = "ORGANIZATION_UPDATED"
    ORGANIZATION_DELETED = "ORGANIZATION_DELETED"

    SCHOOL_CREATED = "SCHOOL_CREATED"
    SCHOOL_UPDATED = "SCHOOL_UPDATED"
    SCHOOL_DELETED = "SCHOOL_DELETED"

    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"

    MEMBERSHIP_CREATED = "MEMBERSHIP_CREATED"
    MEMBERSHIP_UPDATED = "MEMBERSHIP_UPDATED"
    MEMBERSHIP_ENDED = "MEMBERSHIP_ENDED"

    ROLE_CREATED = "ROLE_CREATED"
    ROLE_UPDATED = "ROLE_UPDATED"
    ROLE_DELETED = "ROLE_DELETED"
    ROLE_GRANTED = "ROLE_GRANTED"
    ROLE_REVOKED = "ROLE_REVOKED"

    PERSON_CREATED = "PERSON_CREATED"
    PERSON_UPDATED = "PERSON_UPDATED"
    PERSON_DELETED = "PERSON_DELETED"
    PERSON_MERGED = "PERSON_MERGED"

    ADDRESS_CREATED = "ADDRESS_CREATED"
    ADDRESS_UPDATED = "ADDRESS_UPDATED"
    ADDRESS_DELETED = "ADDRESS_DELETED"

    CONTACT_CREATED = "CONTACT_CREATED"
    CONTACT_UPDATED = "CONTACT_UPDATED"
    CONTACT_DELETED = "CONTACT_DELETED"

    ACADEMIC_YEAR_CREATED = "ACADEMIC_YEAR_CREATED"
    ACADEMIC_YEAR_UPDATED = "ACADEMIC_YEAR_UPDATED"
    ACADEMIC_YEAR_DELETED = "ACADEMIC_YEAR_DELETED"

    ACADEMIC_TERM_CREATED = "ACADEMIC_TERM_CREATED"
    ACADEMIC_TERM_UPDATED = "ACADEMIC_TERM_UPDATED"
    ACADEMIC_TERM_DELETED = "ACADEMIC_TERM_DELETED"

    ACADEMIC_CLASS_CREATED = "ACADEMIC_CLASS_CREATED"
    ACADEMIC_CLASS_UPDATED = "ACADEMIC_CLASS_UPDATED"
    ACADEMIC_CLASS_DELETED = "ACADEMIC_CLASS_DELETED"

    SUBJECT_CREATED = "SUBJECT_CREATED"
    SUBJECT_UPDATED = "SUBJECT_UPDATED"
    SUBJECT_DELETED = "SUBJECT_DELETED"

    CLASS_SUBJECT_CREATED = "CLASS_SUBJECT_CREATED"
    CLASS_SUBJECT_DELETED = "CLASS_SUBJECT_DELETED"

    COHORT_CREATED = "COHORT_CREATED"
    COHORT_UPDATED = "COHORT_UPDATED"
    COHORT_DELETED = "COHORT_DELETED"

    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    LOGOUT = "LOGOUT"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED"
    PASSWORD_RESET_CONFIRMED = "PASSWORD_RESET_CONFIRMED"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SENT = "SENT"
    FAILED = "FAILED"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
